### ISSUE TITLE
plotGenes and plotTranscripts fail with Drosophila dm6 assembly

### ISSUE THREAD

**Issue by tjgibson** [PhanstielLab/plotgardener#53]
Thanks for the great package! I am really excited to start using plotgardener for putting together my figures.
When I try to use the plotGenes or plotTranscripts functions with the Drosophila dm6 assembly I get the following error:

```
Error in `dplyr::left_join()`:
! Can't join on `x$ENTREZID` x `y$ENTREZID` because of incompatible types.
ℹ `x$ENTREZID` is of type <data.frame< ENSEMBL : character ENTREZID: character >>>.
ℹ `y$ENTREZID` is of type <character>>.
---
Backtrace:
 1. plotgardener::plotGenes(...)
 2. plotgardener:::defaultGenePriorities(...)
 6. dplyr:::left_join.data.frame(x = data, y = citationData, by = "ENTREZID")
```

Here is the code I am using: 
```r
library(plotgardener)

## Set genomic coordinates
paramsbig <- pgParams(
  chrom = "chr3R",
  chromstart = 16617140, chromend = 16841732,
  assembly = "dm6", width = 7
)

## Set colors
cols <- c("#41B6C4", "#225EA8")

## Create page
pageCreate(width = 7.5, height = 3.5, default.units = "inches")

## Plot genes big
genesPlot <- plotGenes(
  params = paramsbig, fill = cols,
  x = 0.25, y = 0.25, height = 0.75,
  just = c("left", "top"),
  default.units = "inches"
)

```

The same code works fine if I create a custom assembly for dm6:
```r
library(GenomicFeatures)
library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)
library(BSgenome.Dmelanogaster.UCSC.dm6)
library(org.Dm.eg.db)

# make custom assembly
dm6_custom <- assembly(
  Genome = "dm6_custom",
  TxDb = TxDb.Dmelanogaster.UCSC.dm6.ensGene,
  OrgDb = "org.Dm.eg.db",
  BSgenome = "BSgenome.Dmelanogaster.UCSC.dm6",
  gene.id = "FLYBASE", display.column = "SYMBOL"
)



## Set genomic coordinates
paramsbig <- pgParams(
  chrom = "chr3R",
  chromstart = 16617140, chromend = 16841732,
  assembly = dm6_custom, width = 7
)

## Set colors
cols <- c("#41B6C4", "#225EA8")

## Create page
pageCreate(width = 7.5, height = 3.5, default.units = "inches")

## Plot genes big
genesPlot <- plotGenes(
  params = paramsbig, fill = cols,
  x = 0.25, y = 0.25, height = 0.75,
  just = c("left", "top"),
  default.units = "inches"
)

```
![plotGenes_reprex](https://user-images.githubusercontent.com/37562904/158621676-fcdef63b-a974-4bf9-a96e-70fad7fda7ed.png)

**Comment by nekramer** [comment]
Hi Tyler,

Thanks for checking out the package! I think I found the sources of both of these bugs: (1) looks like the data.frame returned from `select` in `defaultGenePriorities()` had problems in `dplyr` joining, so I made sure to just grab the appropriate column here. The same code would work for a custom assembly since it wouldn't go through the `defaultGenePriorities()` logic, but both should work now; (2) The zoom-in was causing issues when there weren't any genes to be labeled on the opposite strand, so now the function should check to make sure there are genes to label on that strand before proceeding. I've made these changes and pushed them to both `RELEASE_3_14` and `master`. Please let me know if this solves your issue.

Best,
Nicole

**Comment by tjgibson** [comment]
Hi Nicole, 

Thanks for responding so quickly! I tested your changes and everything seems to be working as expected. Closing this issue now.

Tyler
