### ISSUE TITLE
Calling `pageGuideHide` causes the plot to be rendered twice for pdf output

### ISSUE THREAD

**Issue by const-ae** [PhanstielLab/plotgardener#58]
Here is a small `reprex` that demonstrates the issue

``` r
library(grid)
{
  pdf("/tmp/test.pdf", width = 3, height = 3)
  plotgardener::pageCreate( width = 3, height = 3, showGuides = TRUE)
  plotgardener::plotRect(x = unit(0.5, "npc"), y = unit(0.5, "npc"), width = 1.5, height = 1.5, fill = "green")
  dev.off()
}
#> rect[rect1]
#> quartz_off_screen 
#>                 2
pdftools::pdf_info("/tmp/test.pdf")$pages
#> [1] 1
{
  pdf("/tmp/test_with_hide.pdf", width = 3, height =  3)
  plotgardener::pageCreate( width = 3, height = 3)
  plotgardener::plotRect(x = unit(0.5, "npc"), y = unit(0.5, "npc"), width = 1.5, height = 1.5, fill = "green")
  plotgardener::pageGuideHide()
  dev.off()
}
#> rect[rect1]
#> quartz_off_screen 
#>                 2
pdftools::pdf_info("/tmp/test_with_hide.pdf")$pages
#> [1] 2
```

<sup>Created on 2022-05-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Best,
Constantin

**Comment by nekramer** [comment]
Hi Constantin,

Thank you for pointing this out! Unfortunately, this occurs due the nature of the `grid` removal functions that must redraw the entire plot on a new page with specified figures removed. I have tried looking for ways to overcome this, but so far it looks like there is nothing I can personally do to remove this artifact. (If you have any ideas, please let me know!)

If you need a workaround, I would recommend removing all guides before saving to a pdf in the `pageCreate()` function call. Otherwise, I would build the figure interactively and then directly save it to a pdf from the graphics device.

**Comment by const-ae** [comment]
Hi Nicole,

thanks for the reply and thanks for maintaining this package. It makes creating publication ready figures so much easier :)

> Unfortunately, this occurs due the nature of the grid removal functions that must redraw the entire plot on a new page with specified figures removed. I have tried looking for ways to overcome this, but so far it looks like there is nothing I can personally do to remove this artifact. (If you have any ideas, please let me know!)

Interesting. I am still very much a beginner of doing things directly with the `grid` package, so I have no ideas.

>  I would recommend removing all guides before saving to a pdf in the pageCreate() function call

That's a good solution and basically resolves the issue for me. Maybe you could consider adding a short statement on how to work around this issue to the documentation. 

Best,
Constantin

**Comment by nekramer** [comment]
Thank you for this suggestion! I have now added a short explanation about this in the `pageGuideHide` documentation and to the intro vignette around saving plots.
