### ISSUE TITLE
plotPairsArches function

### ISSUE THREAD

**Issue by artemyzhigulev** [PhanstielLab/plotgardener#61]
Hey! Thank you for a nice package :) 
As you can see, in the first example interaction acts a bit strange. Sushi package does not reproduce the same issue.
What can be the problem here?

```
## create one interaction
q=data.frame("chr10",26796593,26861030,"chr10",26735842,26739777)
qq=data.frame("chr21",28140000,28145000,"chr21",28205000,28210000)


## Set the coordinates
params1 <- pgParams(
  chrom = "chr10",
  chromstart = 26700000, chromend = 26900000,
  assembly = "hg19",
  width = 7)

params2 <- pgParams(
  chrom = "chr21",
  chromstart = 28130000, chromend = 28215000,
  assembly = "hg19",
  width = 7)

## Create a page
pageCreate(width = 7.5, height = 5, default.units = "inches")

## Plot the data
archPlot <- plotPairsArches(
  data = q, params = params1,
  x = 0.25, y = 0.25, height = 1.5,
  just = c("left", "top")
)
annoGenomeLabel(plot = archPlot, x = 0.25, y = 1.78, scale = "Kb")

archPlot <- plotPairsArches(
  data = qq, params = params2,
  x = 0.25, y = 2, height = 1.5,
  just = c("left", "top")
)
annoGenomeLabel(plot = archPlot, x = 0.25, y = 3.58, scale = "Kb")
```
<img width="851" alt="Screen Shot 2022-06-03 at 12 51 33" src="https://user-images.githubusercontent.com/100732369/171840485-4f2148e4-d3ee-4dc4-98b6-556faa8c606b.png">

**Comment by nekramer** [comment]
Hi Artemy,

This looks like it was happening due to the heights we defined for the Bezier curves we use to depict these arches. In the first example, the anchors are different sizes and so the standard height for the "inner curve" overlapped the "outer curve" and resulted in points that made this wonky shape. 

I have added better height scaling logic to **version 1.2.5** to scale the arch heights when the anchors are different sizes. Using the same code you provided above, this now results in plots that look like this:
<img width="903" alt="Screen Shot 2022-06-06 at 4 45 48 PM" src="https://user-images.githubusercontent.com/44094608/172245960-0c5bd50a-5dbd-4512-b49f-4b7f6606ef52.png">


Please let me know if you have any additional issues.

Best,
Nicole
