### ISSUE TITLE
Overlayed bigwig tracks

### ISSUE THREAD

**Issue by Knetsy** [PhanstielLab/plotgardener#79]
Hello,

Thank you very much for plotgardener, it makes my life really easier to plot genomic tracks! I wanted to know if it is possible to overlay bigwigs tracks (3 independent biological replicates) in the plotSignal function.

All the best,

Deborah

**Comment by nekramer** [comment]
Hi Deborah,

Happy to hear that `plotgardener` is helpful :) To overlay bigwig tracks, I would recommend using 3 separate calls to `plotSignal` but plot each track with the same genomic region, same y-axis range, and same position and dimensions. This is essentially plotting them on the same track (and since `plotgardener` is coordinate-based, you can feel safe knowing they are all precisely overlaid with one another!). I would recommend changing the opacity of the fill of each track with the `alpha` parameter so you can better see the differences in signal. Here is an example using the datasets from the `plotgardenerData` package:

``` r
library(plotgardener)
#> Warning: package 'plotgardener' was built under R version 4.2.2
#> 
#> Attaching package: 'plotgardener'
#> The following object is masked from 'package:base':
#> 
#>     c
library(plotgardenerData)
data("IMR90_ChIP_H3K27ac_signal")
data("GM12878_ChIP_H3K27ac_signal")

region <- pgParams(
    chrom = "chr21",
    chromstart = 28000000, chromend = 30300000,
    assembly = "hg19",
    range = c(0, 45)
)

pageCreate(width = 7.5, height = 2.1, default.units = "inches", showGuides = FALSE)

signal1 <- plotSignal(
    data = IMR90_ChIP_H3K27ac_signal, params = region,
    fill = "#37a7db", alpha = 0.7, linecolor = NA,
    x = 0.5, y = 0.25, width = 6.5, height = 1.5,
    just = c("left", "top"), default.units = "inches"
)
#> signal[signal1]

signal2 <- plotSignal(
    data = GM12878_ChIP_H3K27ac_signal, params = region,
    fill = "black", linecolor = NA,
    x = 0.5, y = 0.25, width = 6.5, height = 1.5,
    just = c("left", "top"), default.units = "inches"
)
#> signal[signal2]

plotGenomeLabel(
    chrom = "chr21",
    chromstart = 28000000, chromend = 30300000,
    assembly = "hg19",
    x = 0.5, y = 1.85, length = 6.5,
    default.units = "inches"
)
#> genomeLabel[genomeLabel1]
```

![](https://i.imgur.com/5mhLIOI.png)

<sup>Created on 2023-05-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I specified the same region with the `pgParams` object and then plotted these tracks right on top of each other with the same width and height. I hope this helps, and please let me know if you have any other questions!

Best,
Nicole

**Comment by Knetsy** [comment]
Hi Nicole,

Thank you very much! I will give it a try.

Best,

Deborah

**Comment by nekramer** [comment]
Hi Deborah,

Just following up to see if this solved your issue? Otherwise I will be closing the issue.

Best,
Nicole

**Comment by Knetsy** [comment]
Hi Nicole,

Yes it is solved. The solution that you gave me worked very well.  Thank you again and sorry for not reaching out earlier.

All the best,

Deborah
